name: home_business
description: An URfU project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  get: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  liquid_swipe: any
  fluttertoast: any
  flutter_snake_navigationbar: any
  sprintf: any


dev_dependencies:
  flutter_native_splash: any

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
    - family: AvenirNextCyr
      fonts:
        - asset: assets/fonts/AvenirNextCyr-Regular.ttf
        - asset: assets/fonts/AvenirNextCyr-Bold.ttf
        - weight: 700
        - asset: assets/fonts/AvenirNextCyr-Light.ttf
        - weight: 300
        - asset: assets/fonts/AvenirNextCyr-Medium.ttf
        - weight: 500
        - asset: assets/fonts/AvenirNextCyr-UltraLight.ttf
        - weight: 200
