name: home_business
description: An URfU project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  liquid_swipe: any
  fluttertoast: any
  flutter_snake_navigationbar: any
  flutter_slidable: any
  sprintf: any
  shared_preferences: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: any

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true



flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: AvenirNextCyr
      fonts:
        - asset: assets/fonts/AvenirNextCyr-Regular.ttf
        - asset: assets/fonts/AvenirNextCyr-Bold.ttf
        - weight: 700
        - asset: assets/fonts/AvenirNextCyr-BoldItalic.ttf
        - weight: 700
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-Heavy.ttf
        - weight: 900
        - asset: assets/fonts/AvenirNextCyr-HeavyItalic.ttf
        - weight: 900
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-Italic.ttf
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-Light.ttf
        - weight: 300
        - asset: assets/fonts/AvenirNextCyr-LightItalic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-Medium.ttf
        - weight: 500
        - asset: assets/fonts/AvenirNextCyr-MediumItalic.ttf
        - weight: 500
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-Thin.ttf
        - weight: 100
        - asset: assets/fonts/AvenirNextCyr-ThinItalic.ttf
        - weight: 100
        - style: italic
        - asset: assets/fonts/AvenirNextCyr-UltraLight.ttf
        - weight: 200
        - asset: assets/fonts/AvenirNextCyr-UltraLightIt.ttf
        - weight: 200
        - style: italic
          
